spring:
  application:
    name: example-mysql


vline:
  nodes:
    - name: t1
      mysql:
        mode: read
        host: 127.0.0.1
        port: 3306
        database-name: test
        username: root
        password: root
        data-handler: com.codestepfish.vline.example.mysql.MysqlReadExampleHandler

  struct:
    t1:


# t1 mysql read
# MysqlReadExampleHandler 不停查询test表数据
