spring:
  application:
    name: example-postgres


vline:
  nodes:
    - name: t1
      postgres:
        mode: read
        host: 127.0.0.1
        port: 5432
        database-name: postgres
        username: postgres
        password: root
        data-handler: com.codestepfish.vline.example.postgres.PostgresReadExampleHandler

  struct:
    t1:
