spring:
  application:
    name: example-serial-port

vline:
  nodes:
    - name: t1
      extra:
        - id: 1
      type: serial_port
      serial-port:
        device: COM1
        baud-rate: 115200
        ignored: false
        data-handler: com.codestepfish.vline.example.serialport.SerialPortExampleDataHandler
    - name: t2
      type: serial_port
      serial-port:
        device: COM3
        baud-rate: 115200
        data-bits: 8
        stop-bits: 1
        parity: 0
        ignored: true
        data-handler: com.codestepfish.vline.example.serialport.SerialPortExampleDataHandler

  struct:
    t1:
      - t2

# t1 ttyS0
# t2 ttyS1
# 数据互相转发
