spring:
  application:
    name: example-serial-port

vline:
  nodes:
    - name: t1
      extra:
        - id: 1
      type: serial_port
      serial-port:
        device: /dev/ttyS0
        ignored: false
        data-handler: com.codestepfish.vline.example.serialport.SerialPortExampleDataHandler
    - name: t2
      type: serial_port
      serial-port:
        device: /dev/ttyS1
        ignored: true
        data-handler: com.codestepfish.vline.example.serialport.SerialPortExampleDataHandler

  struct:
    t1:
      - t2

# t1 COM1
# t2 COM2
# 数据互相转发
