spring:
  application:
    name: example-mssql


vline:
  nodes:
    - name: t1
      mssql-jtds:
        mode: read
        host: 192.168.88.128
        port: 1433
        database-name: test
        username: sa
        password: sa123456
        flyway: false
        data-handler: com.codestepfish.vline.example.mssql.MssqlReadExampleHandler
    - name: t2
      http:
        handler: com.codestepfish.vline.example.http.HttpExampleHandler
    #    - name: t3
    #      mssql:
    #        mode: read
    #        host: 192.168.88.128
    #        port: 1433
    #        database-name: test
    #        username: sa
    #        password: sa123456
    #        flyway: false
    #        data-handler: com.codestepfish.vline.example.mssql.MssqlWriteExampleHandler
    - name: t4
      mssql:
        mode: read
        host: 192.168.88.128
        port: 1433
        database-name: test
        username: sa
        password: sa123456
        flyway: false
        data-handler: com.codestepfish.vline.example.mssql.MssqlReadExampleHandler2
  struct:
    t4:
#    t1:
#      - t2

