spring:
  application:
    name: example-tcp

vline:
  nodes:
    - name: t1
      extra:
        - id: 1
      type: serial_port
      serial-port:
        device: COM1
        ignored: false
        data-handler: com.codestepfish.vline.example.serialport.SerialPortExampleDataHandler
    - name: t2
      type: serial_port
      serial-port:
        device: COM2
        ignored: true
        data-handler: com.codestepfish.vline.example.serialport.SerialPortExampleDataHandler

  struct:
    t1:
      - t2
