spring:
  application:
    name: example-tcp

# tcp 一进 2出
# tcp 一进 1出
vline:
  enabled: true
  devices:
    - type: tcp
      name: t1
      tags:
        - xx
        - oo
      host: 127.0.0.1
      port: 10001
    - name: t2
      type: tcp
      host: 127.0.0.1
      port: 10010
    - name: t3
      type: tcp
      host: 127.0.0.1
      port: 10011
    - type: tcp
      name: t4
      host: 127.0.0.1
      port: 10086
  topo:
    t1:
      - t2
      - t3
    t4:
      - t3